package form;

import component.DataSearch;
import component.PanelSearch;
import dao.ChuyenDao;
import dao.GaDao;
import dao.TuyenDao;
import entity.Chuyen;
import entity.Ga;
import entity.TaiKhoan;
import event.EvenItemGaClick;
import jakarta.persistence.EntityManagerFactory;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Dimension;
import java.awt.Font;

public class FormMuaVe extends javax.swing.JPanel {

    private EntityManagerFactory emf;
    private MainForm main;
    private GaDao gaDao;
    private JPopupMenu menu;
    private PanelSearch search;
    private List<Ga> listGas;
    private TaiKhoan taiKhoan;

    public FormMuaVe(MainForm main, EntityManagerFactory emf, TaiKhoan taiKhoan) {
        this.emf = emf;
        gaDao = new GaDao(emf);
        this.listGas = gaDao.getAllGa();
        this.taiKhoan = taiKhoan;
        initComponents();
        this.main = main;
        menu = new JPopupMenu();
        search = new PanelSearch();
        menu.setBorder(BorderFactory.createLineBorder(new Color(176, 176, 176)));
        menu.add(search);
        menu.setFocusable(false);
        radBtnMotChieu.setSelected(true);
        ngayVe.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radBtnMotChieu = new javax.swing.JRadioButton();
        radBtnKhuHoi = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ngayDi = new com.toedter.calendar.JDateChooser();
        ngayVe = new com.toedter.calendar.JDateChooser();
        btnTimChuyen = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtGaDi = new javax.swing.JTextField();
        txtGaDen = new javax.swing.JTextField();

        setPreferredSize(new Dimension(1278, 852));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/muaveImgBack.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ga đi");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ga đến");

        buttonGroup1.add(radBtnMotChieu);
        radBtnMotChieu.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        radBtnMotChieu.setText("Một chiều");
        radBtnMotChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnMotChieuActionPerformed(evt);
            }
        });

        buttonGroup1.add(radBtnKhuHoi);
        radBtnKhuHoi.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        radBtnKhuHoi.setText("Khứ hồi");
        radBtnKhuHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnKhuHoiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ngày đi");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ngày về");

        ngayDi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ngayDi.setDateFormatString("dd/MM/yyyy");
        ngayDi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngayDi.setMaxSelectableDate(new java.util.Date(253370743311000L));
        ngayDi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ngayDiFocusGained(evt);
            }
        });

        ngayVe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ngayVe.setDateFormatString("dd/MM/yyyy");
        ngayVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngayVe.setMaxSelectableDate(new java.util.Date(253370743311000L));

        btnTimChuyen.setBackground(new java.awt.Color(204, 204, 255));
        btnTimChuyen.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnTimChuyen.setForeground(new java.awt.Color(102, 102, 255));
        btnTimChuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnTimChuyen.setText("Tìm kiếm");
        btnTimChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimChuyenActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new Font("SansSerif", Font.BOLD, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thông tin hành trình");

        txtGaDi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtGaDi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGaDiMouseClicked(evt);
            }
        });
        txtGaDi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGaDiKeyReleased(evt);
            }
        });

        txtGaDen.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtGaDen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGaDenMouseClicked(evt);
            }
        });
        txtGaDen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGaDenKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addGap(68)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(134)
        							.addComponent(radBtnKhuHoi))
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(txtGaDen, Alignment.LEADING)
        							.addComponent(txtGaDi, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))))
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addGap(120)
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addGap(136)
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addGap(50)
        					.addComponent(ngayDi, GroupLayout.PREFERRED_SIZE, 251, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addGap(55)
        					.addComponent(ngayVe, GroupLayout.PREFERRED_SIZE, 251, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addGap(131)
        					.addComponent(jLabel4))
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addGap(136)
        					.addComponent(jLabel5))
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addGap(77)
        					.addComponent(btnTimChuyen))
        				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        					.addGap(22)
        					.addComponent(radBtnMotChieu)))
        			.addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
        			.addGap(38)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(txtGaDi, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        			.addGap(39)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(txtGaDen, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        			.addGap(45)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(radBtnMotChieu)
        				.addComponent(radBtnKhuHoi))
        			.addGap(26)
        			.addComponent(jLabel4)
        			.addGap(18)
        			.addComponent(ngayDi, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        			.addGap(35)
        			.addComponent(jLabel5)
        			.addGap(18)
        			.addComponent(ngayVe, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        			.addGap(52)
        			.addComponent(btnTimChuyen, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 884, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        			.addGap(5))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 837, Short.MAX_VALUE)
        				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 1278, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 847, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(22, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents


    private void radBtnKhuHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnKhuHoiActionPerformed
        // TODO add your handling code here:
        if (radBtnKhuHoi.isSelected()) {
            ngayVe.setEnabled(true);
        }
    }//GEN-LAST:event_radBtnKhuHoiActionPerformed

    private void ngayDiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ngayDiFocusGained

    }//GEN-LAST:event_ngayDiFocusGained

    private void btnTimChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimChuyenActionPerformed
        String gaDi = txtGaDi.getText();
        String gaDen = txtGaDen.getText();
        Ga ga1 = gaDao.getGaByTen(gaDi);
        Ga ga2 = gaDao.getGaByTen(gaDen);
        if(ga1 == null) {
        	JOptionPane.showMessageDialog(null, "Ga không tồn tại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        	return;
        }
        if(ga2 == null) {
        	JOptionPane.showMessageDialog(null, "Ga không tồn tại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        	return;
        }
        if(ga1.getId() == ga2.getId()) {
        	JOptionPane.showMessageDialog(null, "Ga đi không được trùng với ga đến", "Thông báo", JOptionPane.WARNING_MESSAGE);
        	return;
        }
        if (ngayDi.getDate() == null) {
			JOptionPane.showMessageDialog(null, "Chưa chọn ngày đi", "Thông báo",
					JOptionPane.INFORMATION_MESSAGE);
			return;
		}
        if (ngayVe.getDate() == null && radBtnKhuHoi.isSelected()) {
			JOptionPane.showMessageDialog(null, "Chưa chọn ngày về", "Thông báo",
					JOptionPane.INFORMATION_MESSAGE);
			return;
		}
        
        List<String> listTuyens = new TuyenDao(emf).layTuyenChuaGa(ga1.getId(), ga2.getId());
        if(listTuyens.size() == 0) {
        	JOptionPane.showMessageDialog(null, "Không có tàu đi tuyến của bạn", "Thông báo",
					JOptionPane.INFORMATION_MESSAGE);
			return;
        }
        LocalDate ngayHT = LocalDate.now();
        LocalDate ngDi = ngayDi.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if(ngDi.isBefore(ngayHT) || ngDi.isEqual(ngayHT)) {
        	JOptionPane.showMessageDialog(null, "Chọn ngày sau ngày hiện tại", "Thông báo",
					JOptionPane.INFORMATION_MESSAGE);
			return;
        }
        LocalDate ngVe = null;
        if(radBtnKhuHoi.isSelected()) {
        	ngVe = ngayVe.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        	if(!ngVe.isAfter(ngDi)) {
        		JOptionPane.showMessageDialog(null, "Ngày về phải sau ngày đi", "Thông báo",
    					JOptionPane.INFORMATION_MESSAGE);
    			return;
        	}
        }
        List<Chuyen> listChuyenDis = new ArrayList<Chuyen>();
        for(String maTuyen:listTuyens) {
        	List<Chuyen> listtam = new ChuyenDao(emf).getAllChuyenByNgay(ngDi, ga1.getId() < ga2.getId(),maTuyen); 	
        	listChuyenDis.addAll(listtam);
        }
        if(listChuyenDis.size() == 0) {
        	JOptionPane.showMessageDialog(null, "Không tìm thấy chuyến phù hợp!", "Thông báo",
					JOptionPane.INFORMATION_MESSAGE);
			return;
        }
        List<Chuyen> listChuyenVes = new ArrayList<Chuyen>();
        if(ngVe != null) {
        	for(String maTuyen:listTuyens) {
            	List<Chuyen> listtam = new ChuyenDao(emf).getAllChuyenByNgay(ngVe, ga1.getId() > ga2.getId(),maTuyen); 	
            	listChuyenVes.addAll(listtam);
            }
        	if(listChuyenVes.size() == 0) {
            	JOptionPane.showMessageDialog(null, "Không tìm thấy chuyến về!", "Thông báo",
    					JOptionPane.INFORMATION_MESSAGE);
    			return;
            }
        }
        
        main.showForm(new FormChonTau(emf,main,listChuyenDis,ga1,ga2,ngDi,ngVe,radBtnMotChieu.isSelected(),taiKhoan));
    }//GEN-LAST:event_btnTimChuyenActionPerformed

    private void radBtnMotChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnMotChieuActionPerformed
        // TODO add your handling code here:
        if (radBtnMotChieu.isSelected()) {
            ngayVe.setEnabled(false);
        }
    }//GEN-LAST:event_radBtnMotChieuActionPerformed

    private void txtGaDiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGaDiMouseClicked
    	String text = txtGaDi.getText().toLowerCase();
        search.setData(search(text));
        if(search.getItemSize() > 0){
            menu.show(txtGaDi, 0, txtGaDi.getHeight());
            menu.setPopupSize(252, (search.getItemSize() * 45));
        }
    }//GEN-LAST:event_txtGaDiMouseClicked

    private void txtGaDenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGaDenMouseClicked
    	String text = txtGaDen.getText().toLowerCase();
        search.setData(search(text));
        if(search.getItemSize() > 0){
            menu.show(txtGaDen, 0, txtGaDen.getHeight());
            menu.setPopupSize(252, (search.getItemSize() * 45));
        }
    }//GEN-LAST:event_txtGaDenMouseClicked

    private void txtGaDiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGaDiKeyReleased
        search.addEventClick(new EvenItemGaClick() {
            public void itemClick(DataSearch data) {
            	menu.setVisible(false);
                txtGaDi.setText(data.getText());
            }
        });
        String text = txtGaDi.getText().toLowerCase();
        search.setData(search(text));
        if (search.getItemSize() >= 0) {
            menu.show(txtGaDi, 0, txtGaDi.getHeight());
            menu.setPopupSize(252, (search.getItemSize() * 45));
        }
    }//GEN-LAST:event_txtGaDiKeyReleased

    private void txtGaDenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGaDenKeyReleased
        search.addEventClick(new EvenItemGaClick() {
            public void itemClick(DataSearch data) {
            	menu.setVisible(false);
                txtGaDen.setText(data.getText());
            }
        });
        String text = txtGaDen.getText().toLowerCase();
        search.setData(search(text));
        if (search.getItemSize() >= 0) {
            menu.show(txtGaDen, 0, txtGaDen.getHeight());
            menu.setPopupSize(252, (search.getItemSize() * 45));
        }
    }//GEN-LAST:event_txtGaDenKeyReleased

    private List<DataSearch> search(String text) {
        int limitData = 5;
        List<DataSearch> list = new ArrayList<DataSearch>();
        if (text.equalsIgnoreCase("")) {
            return list;
        }
        for (Ga a : listGas) {
            if (a.getTenGa().toLowerCase().contains(text)) {
                list.add(new DataSearch(a.getTenGa()));
                if (list.size() == limitData) {
                    break;
                }
            }
        }
        return list;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimChuyen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser ngayDi;
    private com.toedter.calendar.JDateChooser ngayVe;
    private javax.swing.JRadioButton radBtnKhuHoi;
    private javax.swing.JRadioButton radBtnMotChieu;
    private javax.swing.JTextField txtGaDen;
    private javax.swing.JTextField txtGaDi;
    // End of variables declaration//GEN-END:variables
}
