/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.util.Rotation;
import org.jfree.data.category.DefaultCategoryDataset;

import dao.KhachHangDao;
import dao.VeDao;
import entity.ChiTietVe;
import entity.Ga;
import entity.Ve;
import jakarta.persistence.EntityManagerFactory;
import swing.ScrollBar;

import java.awt.Dimension;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author HOANG
 */
public class GD_ThongKeLuotVe extends javax.swing.JPanel {

	/**
	 * Creates new form GD_ThongKeLuotVe
	 */
	private EntityManagerFactory emf;
	private VeDao veDao;
	private KhachHangDao khachHangDao;
	private GD_DoiTra gD_DoiTra;

	public GD_ThongKeLuotVe(EntityManagerFactory emf) {
		this.emf = emf;
		initComponents();
		jTable1.setShowGrid(false);
		jTable1.setShowHorizontalLines(false);
		jTable1.setShowVerticalLines(false);
		jTable1.getTableHeader().setFont(new Font("SansSerif", Font.PLAIN, 16));
		jTable1.getTableHeader().setPreferredSize(new Dimension(30, 30));
		jScrollPane1.setVerticalScrollBar(new ScrollBar());
		((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
		veDao = new VeDao(emf);
		khachHangDao = new KhachHangDao(emf);
		gD_DoiTra = new GD_DoiTra(emf);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        panelBarChart = new javax.swing.JPanel();
        chartPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();

		setBackground(new java.awt.Color(43, 84, 100));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("THỐNG KÊ");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số lượt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tổng lượt khách");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tổng số vé đã đặt");

		jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

		jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(21)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)
        						.addGap(47))
        					.addGroup(Alignment.LEADING, jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(jTextField2, Alignment.LEADING)
        						.addComponent(jTextField1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
        				.addComponent(jLabel2))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(25)
        			.addComponent(jLabel2)
        			.addGap(18)
        			.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addGap(41)
        			.addComponent(jLabel3)
        			.addGap(18)
        			.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        panelBarChart.setBackground(new java.awt.Color(255, 255, 255));
        panelBarChart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biểu đồ tỷ lệ hành khách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        panelBarChart.setLayout(new java.awt.BorderLayout());

        chartPanel.setBackground(new java.awt.Color(255, 255, 255));
        chartPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thống kê lượt vé trong tháng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        chartPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chuyến đi nhiều nhất trong tháng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(507, 400));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Chuyến", "Số lượt"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 285, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 384, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        jMonthChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMonthChooser1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 1563, GroupLayout.PREFERRED_SIZE)
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addGap(15)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 239, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 305, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(panelBarChart, GroupLayout.PREFERRED_SIZE, 570, GroupLayout.PREFERRED_SIZE))
        				.addComponent(chartPanel, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 1160, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 418, GroupLayout.PREFERRED_SIZE)
        					.addComponent(panelBarChart, GroupLayout.PREFERRED_SIZE, 428, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(chartPanel, GroupLayout.PREFERRED_SIZE, 289, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(19, Short.MAX_VALUE))
        );
        this.setLayout(layout);

        jPanel1.getAccessibleContext().setAccessibleName("Số lượng chi tiết");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleName("Số lượng chi tiết");
    }// </editor-fold>//GEN-END:initComponents

	private void jMonthChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_jMonthChooser1PropertyChange
		DefaultCategoryDataset dataset = new DefaultCategoryDataset();

		
		
		
		
		int tongSoLuotVe = 0;
		for (int i = 1; i <= 30; i++) {
//			chỗ này +1 => +2
			dataset.setValue(
					((Long) veDao.layTongVeTrongNgay(jYearChooser1.getYear(), jMonthChooser1.getMonth() + 2, i))
							.intValue(),
					"Ngày", i + "");
			tongSoLuotVe += ((Long) veDao.layTongVeTrongNgay(jYearChooser1.getYear(), jMonthChooser1.getMonth() + 2, i))
					.intValue();
		}

		//=================BIỂU ĐỒ CỘT====================
		JFreeChart chart = ChartFactory.createBarChart("", "Tháng " + (jMonthChooser1.getMonth() + 1),
				"Số lượng vé đã bán", dataset, PlotOrientation.VERTICAL, false, true, false);
 
		CategoryPlot categoryPlot = chart.getCategoryPlot();
		categoryPlot.setBackgroundPaint(Color.WHITE);
		categoryPlot.setOutlineVisible(false);
		BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
		Color clr3 = new Color(0, 204, 204);
		renderer.setSeriesPaint(0, clr3);

		NumberAxis rangeAxis = (NumberAxis) categoryPlot.getRangeAxis();
		rangeAxis.setRange(0, 50);

		ChartPanel barpChartPanel = new ChartPanel(chart);
		barpChartPanel.setBorder(null);
		chartPanel.removeAll();
		chartPanel.add(barpChartPanel, BorderLayout.CENTER);
		chartPanel.validate();
                //=====================================
        DefaultPieDataset barDataset = new DefaultPieDataset( );
        int sv = (int) veDao.countDoiTuongByMonthYear(jMonthChooser1.getMonth()+1, jYearChooser1.getYear(), "Sinh viên");
        int nl = (int) veDao.countDoiTuongByMonthYear(jMonthChooser1.getMonth()+1, jYearChooser1.getYear(), "Người lớn");
        int te = (int) veDao.countDoiTuongByMonthYear(jMonthChooser1.getMonth()+1, jYearChooser1.getYear(), "Trẻ em");
        int ng = (int) veDao.countDoiTuongByMonthYear(jMonthChooser1.getMonth()+1, jYearChooser1.getYear(), "Người già");
        
        barDataset.setValue( "Sinh viên" , sv);  
        barDataset.setValue( "Người lớn" , nl);   
        barDataset.setValue( "Trẻ em" , te);   
        barDataset.setValue( "Người cao tuổi" , ng);  
      
		jTextField1.setFont(new Font("Consalas", Font.BOLD, 18));
		jTextField1.setText(sv+nl+te + ng + "");
		jTextField1.setEditable(false);
		jTextField2.setFont(new Font("Consalas", Font.BOLD, 18));
		jTextField2.setText(tongSoLuotVe + "");
		jTextField2.setEditable(false);
		
      //===================BIỂU ĐỒ TRÒN==================
        JFreeChart piechart = ChartFactory.createPieChart(null, barDataset, false,true,false);//explain
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
       //changing pie chart blocks colors
        piePlot.setSectionPaint("Sinh viên", new Color(100,149,237));
        piePlot.setSectionPaint("Trẻ em", new Color(30,144,255));
        piePlot.setSectionPaint("Người lớn", new Color(135,206,250));
        piePlot.setSectionPaint("Người cao tuổi", new Color(135,180,250));
       
        piePlot.setBackgroundPaint(Color.white);
        piePlot.setOutlineVisible(false);
        piePlot.setLabelGenerator(new StandardPieSectionLabelGenerator("{0} {1} ({2})"));
        piePlot.setLabelPaint(Color.BLUE);
        piePlot.setLabelBackgroundPaint(Color.cyan);
        piePlot.setLabelFont(new Font("Conslas", Font.ITALIC, 16));
        
        piePlot.setExplodePercent("Sinh viên", 0.1); // Explode Sinh viên section slightly
        piePlot.setExplodePercent("Trẻ em", 0.1); // Explode Trẻ em section slightly
        piePlot.setExplodePercent("Người lớn", 0.1); // Explode Người lớn section slightly
        piePlot.setExplodePercent("Người cao tuổi", 0.1);
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        barChartPanel.setPreferredSize(new Dimension(300, 300));
        panelBarChart.removeAll();
        panelBarChart.add(barChartPanel, BorderLayout.CENTER);
        panelBarChart.validate();
        
        //====================Hiển thị bảng Số lượt Chuyến===============
        Map<String, Long> veCountByGa = getVeCountByGaChieuDiChieuDen();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Xóa tất cả các hàng cũ nếu có

        for (Map.Entry<String, Long> entry : veCountByGa.entrySet()) {
            Object[] row = {entry.getKey(), entry.getValue()};
            model.addRow(row);
        }
        model.fireTableDataChanged();
        
	}// GEN-LAST:event_jMonthChooser1PropertyChange
	
	//=========ĐẾM TỔNG VÉ THEO CHUYẾN===========
	public Map<String, Long> getVeCountByGaChieuDiChieuDen() {
        List<Ve> veList = veDao.layDSVe();
        Map<String, Long> gaCountMap = new HashMap<>();
// 		chỗ này như trên
        int month = jMonthChooser1.getMonth()+2;
        int year = jYearChooser1.getYear();
        
        for (Ve ve : veList) {
            if (!ve.isTrangThai())
                continue;

            if (ve.getThoiGianLenTau().getMonth().getValue() == month
            		&& ve.getThoiGianLenTau().getYear() == year) {
				

            Set<ChiTietVe> listChiTietVes = ve.getLisChiTietVes();
            Ga gaChieuDi = null;
            Ga gaChieuDen = null;

            for (ChiTietVe ctv : listChiTietVes) {
                if (ctv.isChieu())
                    gaChieuDi = ctv.getGa();
                else
                    gaChieuDen = ctv.getGa();
            }

            if (gaChieuDi != null && gaChieuDen != null) {
                String key = gaChieuDi.getTenGa() + " - " + gaChieuDen.getTenGa();
                gaCountMap.put(key, gaCountMap.getOrDefault(key, 0L) + 1);
            }
			}
        }

        return gaCountMap.entrySet()
                .stream()
                .sorted(Map.Entry.<String, Long>comparingByValue().reversed())
                .collect(Collectors.toMap(
                        Map.Entry::getKey,
                        Map.Entry::getValue,
                        (e1, e2) -> e1,
                        LinkedHashMap::new
                ));
    }

	@Override
	protected void paintChildren(Graphics g) {
		Graphics2D g2 = (Graphics2D) g;
		g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
		GradientPaint g3 = new GradientPaint(0, 0, Color.decode("#6699CC"), 0, getHeight(), Color.decode("#6699CC"));
		g2.setPaint(g3);
		g2.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);
		super.paintChildren(g);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JPanel panelBarChart;

}
